### ISSUE TITLE
FEATURE - Remote config file

### ISSUE THREAD

**Issue by evairmarinho** [terraform-linters/tflint#1721] opened 2023-03-19 02:03 UTC
I would love to have a common centralized `.tflint.hcl` for all my Terraform projects. TFlint could give the option to pull configuration from a remote git repository. However, I would like TFLint to be able to merge the "global" settings with specific settings for each Terraform project, in case it is necessary to enable or disable a rule.

```hcl
config {
  source = "https://github.com/my-org/devops-global-configs/blob/main/.tflint.hcl"
}

# Additional Rule that override "global" configuration. Only a example.
rule "terraform_standard_module_structure" {
    enabled = false
}
```
In `tfsec` there is an implementation of this via CLI, via the parameter `--config-file-url` . 

Ref of implementation: https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/cmd/flags.go . Search for `configFileUrl`

_Originally posted by @evairmarinho in https://github.com/terraform-linters/tflint/discussions/1720_

**Comment by wata727** [comment] 2023-03-19 07:16
Duplicate of https://github.com/terraform-linters/tflint/discussions/1720

**Closed by wata727** 2023-03-19 07:16 UTC
