### ISSUE TITLE
OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [terraform-linters/tflint#1832] opened 2023-08-29 19:35 UTC
https://opentf.org/announcement

We want to understand how tflint is affected by the OpenTF announcement, and what the plans for support are moving forward.

**Comment by bendrucker** [comment] 2023-08-29 22:05
Duplicate of https://github.com/terraform-linters/tflint/discussions/1826

**Closed by bendrucker** 2023-08-29 22:05 UTC
