### ISSUE TITLE
install_linux.sh - "unzip: unrecognized option: u" error

### ISSUE THREAD

**Issue by fabasoad** [terraform-linters/tflint#1249] opened 2021-11-05 02:20 UTC
## Problem

I am running [installation command](https://github.com/terraform-linters/tflint#installation) taken from README file on a Linux Alpine machine but have the error message below.

```console
$ curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
os=linux_amd64
====================================================
Looking up the latest version ...
Downloading TFLint v0.33.1
Downloaded successfully
====================================================
Unpacking /tmp/tflint.zip ...
unzip: unrecognized option: u
BusyBox v1.31.1 () multi-call binary.
Usage: unzip [-lnojpq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]
Extract FILEs from ZIP archive
	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-j	Do not restore paths
	-p	Print to stdout
	-q	Quiet
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
Installing /tmp/tflint to /usr/local/bin/...
install: can't stat '/tmp/tflint': No such file or directory
Failed to install tflint
```

## Version

```console
$ terraform -v
Terraform v0.14.4
```

**Comment by bendrucker** [comment] 2021-11-05 03:26
Duplicate of https://github.com/terraform-linters/tflint/issues/1050

**Closed by bendrucker** 2021-11-05 03:26 UTC
